// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBuIzGMU_ngluqsuhqvZripO_JpXW_KDA',
    appId: '1:547812847012:web:a11fdb12ace1b44dfba531',
    messagingSenderId: '547812847012',
    projectId: 'car-ads-a3d2e',
    authDomain: 'car-ads-a3d2e.firebaseapp.com',
    storageBucket: 'car-ads-a3d2e.firebasestorage.app',
    measurementId: 'G-EH6Y6EBKWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6KnO2Giw0ALdH1TABLxoTKfBnWOkeudY',
    appId: '1:547812847012:android:316e2bed4c28b0f8fba531',
    messagingSenderId: '547812847012',
    projectId: 'car-ads-a3d2e',
    storageBucket: 'car-ads-a3d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00gs-cG9ZxgkhcyKgGcNHvMpcaZZI9Os',
    appId: '1:547812847012:ios:05f750e5f9e9426afba531',
    messagingSenderId: '547812847012',
    projectId: 'car-ads-a3d2e',
    storageBucket: 'car-ads-a3d2e.firebasestorage.app',
    iosBundleId: 'com.example.carAds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00gs-cG9ZxgkhcyKgGcNHvMpcaZZI9Os',
    appId: '1:547812847012:ios:05f750e5f9e9426afba531',
    messagingSenderId: '547812847012',
    projectId: 'car-ads-a3d2e',
    storageBucket: 'car-ads-a3d2e.firebasestorage.app',
    iosBundleId: 'com.example.carAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBuIzGMU_ngluqsuhqvZripO_JpXW_KDA',
    appId: '1:547812847012:web:18e389082475caeefba531',
    messagingSenderId: '547812847012',
    projectId: 'car-ads-a3d2e',
    authDomain: 'car-ads-a3d2e.firebaseapp.com',
    storageBucket: 'car-ads-a3d2e.firebasestorage.app',
    measurementId: 'G-403D3BSTN1',
  );
}
